import type { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'
import { Rubik, Rubik_Mono_One } from 'next/font/google'
import TransitionProvider from './components/TransitionProvider.tsx/TransitionProvider'
import './globals.css'

const rubik = Rubik({
	weight: ['400', '500', '700'],
	subsets: ['latin'],
	variable: '--font-rubik',
})

const rubikMono = Rubik_Mono_One({
	weight: ['400'],
	subsets: ['latin'],
	variable: '--font-rubik-mono',
})

export const metadata: Metadata = {
	title: 'WebLazyTeam — аутсорсинг веб-разработки',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			suppressHydrationWarning
			lang='ru'
			className='overflow-x-hidden min-w-[320px]'
		>
			<body className={`${rubik.variable} ${rubikMono.variable}`}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					<TransitionProvider>{children}</TransitionProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
