import type { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'
import { Rubik_Mono_One } from 'next/font/google'
import TransitionProvider from './components/TransitionProvider.tsx/TransitionProvider'
import './globals.css'
const rubikMonoOne = Rubik_Mono_One({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
	title: 'WebLazyTeam — аутсорсинг веб-разработки',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html suppressHydrationWarning lang='ru'>
			<body className={rubikMonoOne.className}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					<TransitionProvider>{children}</TransitionProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
